trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g firebase-tools
    npm install
    npm run build
  displayName: 'npm install Firebase and build'

- script: |
    firebase deploy --token $(FIREBASE_TOKEN)
  displayName: 'firebase token inclusion'

env:
  FIREBASE_TOKEN: $(FIREBASE_TOKEN)