trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Escolha a imagem de máquina adequada

steps:
- task: NodeTool@0
  inputs:
   versionSpec: '20.x'

- script: |
   npm install -g firebase-tools
  displayName: 'Instalar Firebase CLI'

- script: |
   npm install
  displayName: 'Instalar dependências'

- script: |
   firebase deploy --token $(FIREBASE_TOKEN)
   echo "Token: $(FIREBASE_TOKEN)"
  displayName: 'Inclusao do Token do Firebase'